export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Projects } from './projects/Projects'
export { default as Skills } from './skills/Skills'
export { default as Certificates } from './certificates/Certificates'
export { default as Contact } from './contact/Contact'